import React, {useState, useMemo} from 'react';
import ReactDOM from 'react-dom';
import DocumentGrid from './DocumentGrid';
import DocumentCommandBar from './DocumentCommandBar';
import DocumentThumbnail from './DocumentThumbnail';
import DocumentPerson from './DocumentPerson';
import {UserPhotoProvider} from './UserPhotos';
import { FluentProvider, webLightTheme, webDarkTheme, teamsHighContrastTheme, createLightTheme, makeStyles, mergeClasses, tokens, Button, Text, Badge, Checkbox, Tooltip, Menu, MenuTrigger, MenuPopover, MenuList, MenuItem, MenuDivider, MenuItemRadio, Card, Dialog, DialogSurface, DialogBody, DialogTitle, DialogContent, DialogActions, Field, Input, Dropdown, Option, Textarea, ProgressBar, Toolbar, ToolbarGroup, InlineDrawer, OverlayDrawer, DrawerBody, DrawerHeader, DrawerHeaderTitle, DrawerFooter } from '@fluentui/react-components';
import { AddRegular, ArrowUploadRegular, ArrowSyncRegular, MoreHorizontalRegular, ChevronDownRegular, FilterRegular, InfoRegular, ArrowMaximizeRegular, ArrowMinimizeRegular, GridRegular, TextBulletListRegular, LibraryRegular, DocumentRegular, DismissRegular, OpenRegular, EyeRegular, ArrowDownloadRegular, LinkRegular, DeleteRegular, EditRegular, GlobeRegular, CheckmarkRegular, ArrowLeftRegular, WarningRegular, FolderRegular, SearchRegular } from '@fluentui/react-icons';

const teal = createLightTheme({10:'#001d1e',20:'#003034',30:'#004549',40:'#00575c',50:'#00696f',60:'#00666b',70:'#00757a',80:'#008489',90:'#149399',100:'#2ba4a9',110:'#5cd0d6',120:'#7edce0',130:'#a1e6e9',140:'#beeef0',150:'#d9f5f6',160:'#eefbfb'});
const documents = [
['Master Services Agreement.docx','Word','W','Contract','Active','October 24, 2026','4 minutes ago','Michael Bose','Note','1.4 MB','Legal'],
['Q3 Proposal.pptx','PowerPoint','P','Proposal','Draft','—','2 hours ago','Alex Wilber','Note','3.8 MB','Sales'],
['Pricing Model.xlsx','Excel','X','Finance','Active','—','Yesterday at 3:42 PM','Irvin Sayers','Note','248 KB','Finance'],
['Signed NDA.pdf','PDF','PDF','Legal','Active','Expired','September 24, 2026','Michael Bose','Note','820 KB','Legal'],
['Insurance Certificate.pdf','PDF','PDF','Legal','Active','April 22, 2027','September 20, 2026','MOD Administrator','Note','1.1 MB','Legal'],
['Statement of Work.docx','Word','W','Contract','Active','—','September 18, 2026','Alex Wilber','SharePoint','—','Sales'],
['Site Photo.jpg','Photo','IMG','Media','Active','—','September 16, 2026','Adele Vance','Note','2.6 MB','Operations'],
['Board Deck.pptx','PowerPoint','P','Proposal','Draft','—','September 14, 2026','MOD Administrator','SharePoint','—','Sales'],
['Meeting Notes.txt','Text','TXT','Other','Active','—','September 12, 2026','Megan Bowen','Note','12 KB','Operations'],
['Budget 2026.xlsx','Excel','X','Finance','Active','—','September 10, 2026','Irvin Sayers','SharePoint','—','Finance'],
['Team Notebook','Link','↗','Other','Active','—','September 8, 2026','Megan Bowen','SharePoint','—','Operations'],
['Failed Upload.pdf','PDF','PDF','Other','Failed','—','September 6, 2026','Michael Bose','Note','—','Legal'],
].map((d,id)=>({id,name:d[0],fileType:d[1],glyph:d[2],type:d[3],status:d[4],expiry:d[5],modified:d[6],by:d[7],source:d[8],size:d[9],department:d[10]}));
const useStyles = makeStyles({
 page:{minHeight:'100vh',backgroundColor:tokens.colorNeutralBackground2,color:tokens.colorNeutralForeground1,fontFamily:tokens.fontFamilyBase},
 review:{padding:'12px 28px',display:'flex',alignItems:'center',justifyContent:'space-between',gap:'16px',backgroundColor:tokens.colorNeutralBackground1,borderBottom:`1px solid ${tokens.colorNeutralStroke2}`,flexWrap:'wrap'},
 reviewTitle:{display:'flex',alignItems:'center',gap:'10px'}, controls:{display:'flex',alignItems:'center',gap:'8px',flexWrap:'wrap'}, controlLabel:{fontSize:'12px',color:tokens.colorNeutralForeground2},
 form:{maxWidth:'1480px',margin:'0 auto',padding:'32px 48px 42px','@media(max-width:720px)':{padding:'18px 12px'}},
 breadcrumb:{display:'flex',alignItems:'center',gap:'8px',fontSize:'12px',color:tokens.colorNeutralForeground2,marginBottom:'18px'},
 account:{display:'flex',alignItems:'center',gap:'14px',marginBottom:'24px'}, accountIcon:{width:'44px',height:'44px',display:'grid',placeItems:'center',backgroundColor:tokens.colorBrandBackground2,color:tokens.colorBrandForeground1,borderRadius:tokens.borderRadiusMedium,fontSize:'20px'},
 accountTitle:{fontSize:'24px',fontWeight:tokens.fontWeightSemibold,lineHeight:'32px'}, secondary:{color:tokens.colorNeutralForeground2,fontSize:'12px'},
 tabs:{display:'flex',gap:'28px','@media(max-width:720px)':{gap:'18px'},borderBottom:`1px solid ${tokens.colorNeutralStroke2}`,marginBottom:'26px'}, tab:{padding:'0 0 12px',color:tokens.colorNeutralForeground2,fontSize:'14px'}, activeTab:{borderBottom:`3px solid ${tokens.colorBrandStroke1}`,color:tokens.colorNeutralForeground1,fontWeight:tokens.fontWeightSemibold},
 sectionLabel:{marginBottom:'20px',fontSize:'13px',color:tokens.colorNeutralForeground2}, library:{backgroundColor:tokens.colorNeutralBackground1,borderRadius:tokens.borderRadiusNone,overflow:'hidden',minHeight:'730px'}, expanded:{position:'fixed',inset:'12px',zIndex:10,boxShadow:tokens.shadow64},
 heading:{display:'flex',alignItems:'center',gap:'10px',padding:'24px 24px 20px'}, title:{fontSize:'24px',fontWeight:tokens.fontWeightSemibold,lineHeight:'32px'}, count:{fontSize:'14px',color:tokens.colorNeutralForeground3}, chip:{backgroundColor:tokens.colorBrandBackground2,color:tokens.colorBrandForeground1,minWidth:'40px'},
 toolbar:{display:'flex',alignItems:'center',justifyContent:'space-between',gap:'8px',padding:'6px 20px',minHeight:'44px',borderBottom:`1px solid ${tokens.colorNeutralStroke2}`,flexWrap:'wrap'}, toolbarGroup:{display:'flex',gap:'4px',alignItems:'center',minHeight:'36px'}, command:{'& svg':{color:tokens.colorBrandForeground1}}, search:{width:'190px','@media(max-width:1000px)':{width:'140px'},'@media(max-width:720px)':{width:'120px'}}, label:{'@media(max-width:1000px)':{display:'none'}},
 workspace:{display:'flex',minHeight:'560px'}, main:{flex:1,minWidth:0}, gridScroll:{overflowX:'auto',width:'100%'}, table:{width:'100%',borderCollapse:'collapse',tableLayout:'fixed',fontSize:'14px',minWidth:'1240px','@media(max-width:720px)':{minWidth:'560px'}}, detailsTable:{minWidth:'760px','@media(max-width:720px)':{minWidth:'560px'}}, th:{height:'44px',textAlign:'left',fontWeight:tokens.fontWeightSemibold,borderBottom:`1px solid ${tokens.colorNeutralStroke2}`,padding:'0 10px',fontSize:'14px'}, headerButton:{fontWeight:tokens.fontWeightSemibold,fontSize:'14px',paddingLeft:0,justifyContent:'flex-start',width:'100%',minWidth:0,whiteSpace:'nowrap','& svg':{fontSize:'12px'}}, row:{height:'46px',borderBottom:`1px solid ${tokens.colorNeutralStroke2}`,cursor:'pointer','&:hover':{backgroundColor:tokens.colorSubtleBackgroundHover},'&:hover .selection':{opacity:1},'&:focus-visible':{outline:`2px solid ${tokens.colorStrokeFocus2}`,outlineOffset:'-2px'}},selected:{backgroundColor:tokens.colorSubtleBackgroundSelected}, td:{padding:'0 10px',whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}, name:{fontSize:'14px','&:hover':{textDecoration:'underline'}}, selection:{opacity:0,'&:focus-within':{opacity:1}},selectionOn:{opacity:1}, checkboxCell:{width:'40px',paddingLeft:'8px'}, iconCell:{width:'36px',padding:'0 2px'}, fileIcon:{width:'24px',height:'28px',flexShrink:0},
 pane:{width:'300px',flexShrink:0,borderLeft:`1px solid ${tokens.colorNeutralStroke2}`,padding:'18px 22px',boxSizing:'border-box','@media(max-width:1000px)':{position:'fixed',top:0,right:0,bottom:0,width:'320px',zIndex:20,backgroundColor:tokens.colorNeutralBackground1,boxShadow:tokens.shadow64,overflowY:'auto'}}, paneHeader:{display:'flex',alignItems:'center',justifyContent:'space-between',marginBottom:'24px'}, paneThumbnail:{height:'172px',marginBottom:'16px',borderRadius:tokens.borderRadiusMedium,overflow:'hidden'}, paneHero:{paddingBottom:'22px',borderBottom:`1px solid ${tokens.colorNeutralStroke2}`}, paneName:{fontSize:'17px',fontWeight:tokens.fontWeightSemibold,margin:'14px 0 8px',overflowWrap:'anywhere'}, paneActions:{display:'flex',gap:'6px',marginTop:'16px'}, paneSection:{padding:'20px 0',borderBottom:`1px solid ${tokens.colorNeutralStroke2}`}, sectionTitle:{fontWeight:tokens.fontWeightSemibold,fontSize:'14px',display:'flex',alignItems:'center',justifyContent:'space-between',marginBottom:'16px'}, props:{display:'grid',gridTemplateColumns:'100px 1fr',gap:'14px 10px',fontSize:'12px'}, hint:{padding:'12px',backgroundColor:tokens.colorNeutralBackground2,borderRadius:tokens.borderRadiusMedium,fontSize:'12px',lineHeight:'18px',marginTop:'16px'},
 footer:{height:'42px',padding:'0 22px',display:'flex',alignItems:'center',justifyContent:'space-between',fontSize:'12px',color:tokens.colorNeutralForeground2},
 tileStrip:{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'10px 16px'}, tiles:{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(192px,1fr))',gap:'16px',padding:'0 20px 20px','@media(max-width:480px)':{gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:'10px',padding:'0 12px 12px'}}, tile:{padding:0,boxShadow:tokens.shadow4,borderRadius:tokens.borderRadiusLarge,transitionProperty:'box-shadow',transitionDuration:tokens.durationNormal,transitionTimingFunction:tokens.curveEasyEase,'&:hover':{boxShadow:tokens.shadow16},'&:focus-within':{boxShadow:tokens.shadow16},'@media(prefers-reduced-motion:reduce)':{transitionDuration:'0ms'},border:`1px solid ${tokens.colorNeutralStroke2}`,cursor:'pointer',position:'relative','&:hover .selection':{opacity:1}}, tileSelected:{boxShadow:tokens.shadow8,border:`2px solid ${tokens.colorBrandStroke1}`,backgroundColor:tokens.colorBrandBackground2}, tilePreview:{height:'136px',backgroundColor:tokens.colorNeutralBackground2,display:'grid',placeItems:'center'},tileBody:{padding:'16px',display:'flex',flexDirection:'column',gap:'8px'},tileName:{fontWeight:tokens.fontWeightRegular,fontSize:'14px',minHeight:'40px',overflowWrap:'anywhere'},tileCheck:{position:'absolute',top:'6px',left:'6px'}, tileMore:{position:'absolute',top:'6px',right:'6px'},
 filter:{padding:'12px 20px',display:'flex',alignItems:'center',gap:'8px',backgroundColor:tokens.colorNeutralBackground2,flexWrap:'wrap'},empty:{textAlign:'center',padding:'90px 24px',color:tokens.colorNeutralForeground2}, notice:{display:'flex',alignItems:'center',gap:'8px',padding:'10px 20px',backgroundColor:tokens.colorBrandBackground2,fontSize:'12px'},
 editDrawer:{width:'420px',maxWidth:'100vw'}, responsiveHide:{'@media(max-width:720px)':{display:'none'}}, detailsHide:{display:'none'}, dialogFields:{display:'flex',flexDirection:'column',gap:'16px',marginTop:'14px'}, preview:{height:'300px',display:'flex',alignItems:'center',justifyContent:'center',flexDirection:'column',gap:'20px',backgroundColor:tokens.colorNeutralBackground2,borderRadius:tokens.borderRadiusMedium},
});
function FileIcon({doc,large=false}) {
 const icons={Word:'WordColorIcon',Excel:'ExcelColorIcon',PowerPoint:'PowerPointColorIcon',PDF:'FilesPdfColoredIcon',Photo:'FilesPictureColoredIcon',Text:'FilesTextColoredIcon'};
 if(doc.fileType==='Link')return <GlobeRegular aria-label="SharePoint link" style={{width:large?48:20,height:large?48:20,color:tokens.colorBrandForeground1}}/>;
 return <img src={`/icons/${icons[doc.fileType]||'FilesGenericColoredIcon'}.svg`} width={large?48:20} height={large?48:20} alt="" title={`${doc.fileType} file`} />;
}
function App(){
 const s=useStyles();
 const [theme,setTheme]=useState('Teal'),[provider,setProvider]=useState('Note'),[view,setView]=useState('List'),[selected,setSelected]=useState([]),[details,setDetails]=useState(false),[query,setQuery]=useState(''),[preset,setPreset]=useState('All documents'),[filter,setFilter]=useState(false),[typeFilter,setTypeFilter]=useState('All types'),[expanded,setExpanded]=useState(false),[dialog,setDialog]=useState(null),[notice,setNotice]=useState(''),[sortAsc,setSortAsc]=useState(null),[rows,setRows]=useState(documents),[showSource,setShowSource]=useState(true);
 const visible=useMemo(()=>{let d=rows.filter(d=>d.name.toLowerCase().includes(query.toLowerCase())&&(typeFilter==='All types'||d.type===typeFilter)&&(preset!=='Expired'||d.expiry==='Expired')&&(preset!=='Expiring soon'||d.expiry==='October 24, 2026')&&(preset!=='Added by me'||d.by==='Michael Bose')&&(preset!=='Recently modified'||['4 minutes ago','2 hours ago','Yesterday at 3:42 PM'].includes(d.modified)));return sortAsc===null?d:[...d].sort((a,b)=>a.name.localeCompare(b.name)*(sortAsc?1:-1));},[rows,query,typeFilter,preset,sortAsc]);
 const picked=rows.filter(d=>selected.includes(d.id)),current=picked[0];
 const select=(id,event,toggle=false)=>{if(event.shiftKey&&selected.length){const a=visible.findIndex(d=>d.id===selected[selected.length-1]),b=visible.findIndex(d=>d.id===id);if(a>=0&&b>=0){setSelected(visible.slice(Math.min(a,b),Math.max(a,b)+1).map(d=>d.id));return;}}setSelected(toggle||event.ctrlKey||event.metaKey?selected.includes(id)?selected.filter(x=>x!==id):[...selected,id]:[id]);};
 const feedback=msg=>{setNotice(msg);};
 const prune=(fn)=>{setSelected([]);fn();};
 const action=(kind)=>{if(kind==='Delete'||kind==='Edit details'||kind==='Preview'||kind==='Open')setDialog(kind);else feedback(`${kind} · Visual demonstration only`);};
 const iconButton=(label,icon,onClick,pressed=false)=><Tooltip content={label} relationship="label"><Button aria-label={label} appearance={pressed?'secondary':'subtle'} icon={icon} onClick={onClick} className={s.command}/></Tooltip>;
 const status=d=><Badge size="medium" appearance="tint" color={d.status==='Failed'?'danger':d.status==='Draft'?'subtle':'success'}>{d.status}</Badge>;
 const head=(label)=><Menu><MenuTrigger disableButtonEnhancement><Button appearance="transparent" icon={<ChevronDownRegular/>} iconPosition="after" className={s.headerButton}>{label}</Button></MenuTrigger><MenuPopover><MenuList><MenuItem onClick={()=>setSortAsc(true)}>Sort A to Z</MenuItem><MenuItem onClick={()=>setSortAsc(false)}>Sort Z to A</MenuItem><MenuDivider/><MenuItem icon={<FilterRegular/>} onClick={()=>setFilter(true)}>Filter by</MenuItem></MenuList></MenuPopover></Menu>;
 return <FluentProvider theme={theme==='Teal'?teal:theme==='Dark'?webDarkTheme:theme==='High contrast'?teamsHighContrastTheme:webLightTheme}>
 <div className={s.page}>
 <div className={s.review}><div className={s.reviewTitle}><LibraryRegular/><Text weight="semibold">DMS Grid</Text><Badge appearance="tint" color="informative">Review 05</Badge><Text className={s.controlLabel}>Sample data</Text></div><div className={s.controls}><span className={s.controlLabel}>Theme</span>{['Teal','Blue','Dark','High contrast'].map(t=><Button key={t} size="small" appearance={theme===t?'primary':'subtle'} onClick={()=>setTheme(t)}>{t}</Button>)}<span className={s.controlLabel}>Add with</span><Button size="small" appearance="secondary" onClick={()=>setProvider(provider==='Note'?'SharePoint':'Note')}>{provider==='Note'?'Notes':'SharePoint links'}<ChevronDownRegular/></Button></div></div>
 <main className={s.form}><div className={s.breadcrumb}>Accounts <span>/</span> <Text weight="semibold">Contoso Ltd</Text></div><div className={s.sectionLabel}>Documents associated with this account</div>
 <section className={mergeClasses(s.library,expanded&&s.expanded)} aria-label="Document library" onKeyDown={e=>{if(e.key==='Escape'){if(dialog)setDialog(null);else if(expanded)setExpanded(false);else setSelected([]);}if((e.ctrlKey||e.metaKey)&&e.key==='a'&&!['INPUT','TEXTAREA'].includes(e.target.tagName)){e.preventDefault();setSelected(visible.map(d=>d.id));}}}>
 <div className={s.heading}><h1 className={s.title} style={{margin:0}}>Documents</h1><span className={s.count}>{rows.length}</span><Menu><MenuTrigger disableButtonEnhancement><Button className={s.chip} appearance="subtle" icon={<LibraryRegular/>} aria-label="Switch view"><ChevronDownRegular/></Button></MenuTrigger><MenuPopover><MenuList>{['List','Tiles'].map(v=><MenuItem key={v} icon={v==='List'?<TextBulletListRegular/>:<GridRegular/>} onClick={()=>setView(v)}>{v} view{view===v?' ✓':''}</MenuItem>)}</MenuList></MenuPopover></Menu></div>
 <DocumentCommandBar provider={provider} selectionCount={selected.length} onAction={action} onUpload={()=>setDialog('Upload')} onAddLink={()=>setDialog('Add link')} onRefresh={()=>feedback('Documents are up to date.')} onClear={()=>setSelected([])} query={query} onSearch={value=>prune(()=>setQuery(value))} preset={preset} onPreset={value=>prune(()=>setPreset(value))} view={view} onView={setView} filters={filter} onFilters={()=>setFilter(!filter)} details={details} onDetails={()=>setDetails(!details)} expanded={expanded} onExpand={()=>setExpanded(!expanded)} feedback={feedback} onColumns={()=>setShowSource(!showSource)} onShortcuts={()=>setDialog('Keyboard shortcuts')}/>
 {notice&&<div role="status" className={s.notice}><CheckmarkRegular/>{notice}<Button size="small" appearance="transparent" icon={<DismissRegular/>} aria-label="Dismiss message" onClick={()=>setNotice('')}/></div>}
 {filter&&<div className={s.filter}><Text size={200}>Document type</Text>{['All types','Contract','Proposal','Finance','Legal','Media','Other'].map(t=><Button key={t} size="small" appearance={typeFilter===t?'primary':'subtle'} onClick={()=>prune(()=>setTypeFilter(t))}>{t}</Button>)}</div>}
 <div className={s.workspace}><div className={s.main}>{view==='List'?<div className={s.gridScroll}><DocumentGrid rows={visible} selected={selected} setSelected={setSelected} select={select} details={details} FileIcon={FileIcon} head={head} onPreview={id=>{setSelected([id]);setDialog('Preview');}} onDetails={id=>{setSelected([id]);setDetails(true);}} feedback={feedback}/></div>:<><div className={s.tileStrip}><Checkbox shape="circular" label="Select all" checked={selected.length===visible.length&&visible.length>0?true:selected.length?'mixed':false} onChange={()=>setSelected(selected.length===visible.length?[]:visible.map(d=>d.id))}/><Button size="small" appearance="subtle" onClick={()=>setSortAsc(!sortAsc)}>Sort: Name <ChevronDownRegular/></Button></div><div className={s.tiles} role="listbox" aria-label="Documents" aria-multiselectable="true">{visible.map(d=><Card key={d.id} role="option" aria-selected={selected.includes(d.id)} tabIndex={0} className={mergeClasses(s.tile,selected.includes(d.id)&&s.tileSelected)} onClick={e=>select(d.id,e)} onDoubleClick={()=>{setSelected([d.id]);setDialog('Preview');}} onKeyDown={e=>{if(e.key===' '){e.preventDefault();select(d.id,e,true);}if(e.key==='Enter'){setSelected([d.id]);setDialog('Preview');}}}><div className={s.tilePreview}><DocumentThumbnail doc={d} icon={<FileIcon doc={d} large/>}/></div><span className={mergeClasses('selection',s.selection,selected.length>0&&s.selectionOn,s.tileCheck)} onClick={e=>e.stopPropagation()}><Checkbox shape="circular" aria-label={`Select ${d.name}`} checked={selected.includes(d.id)} onChange={e=>select(d.id,e,true)}/></span><Button className={s.tileMore} appearance="subtle" icon={<MoreHorizontalRegular/>} aria-label={`Details for ${d.name}`} onClick={e=>{e.stopPropagation();setSelected([d.id]);setDetails(true);}}/><div className={s.tileBody}><div className={s.tileName}>{d.name}</div><DocumentPerson name={d.by}/><Text className={s.secondary}>{d.modified}</Text><div>{status(d)}{d.expiry==='Expired'&&<> <Badge size="small" appearance="tint" color="danger">Expired</Badge></>}</div></div></Card>)}</div></>}
 {!visible.length&&<div className={s.empty}><DocumentRegular fontSize={48}/><h2>No results match your search or filters</h2><Button onClick={()=>{setQuery('');setTypeFilter('All types');setPreset('All documents');}}>Clear filters</Button></div>}<div className={s.footer}><span>{visible.length===rows.length?`${rows.length} items`:`${visible.length} of ${rows.length} items`}</span><span>All documents loaded</span></div></div>
 {details&&<InlineDrawer open position="end" className={s.pane} aria-label="Document details"><div className={s.paneHeader}><Text weight="semibold">Details</Text>{iconButton('Close details',<DismissRegular/>,()=>setDetails(false))}</div>{current&&selected.length===1?<><div className={s.paneHero}><div className={s.paneThumbnail}><DocumentThumbnail doc={current} icon={<FileIcon doc={current} large/>}/></div><div className={s.paneName}>{current.name}</div><Text className={s.secondary}>{current.fileType} document · {current.size}</Text><div className={s.paneActions}><Button size="small" icon={<OpenRegular/>} onClick={()=>action('Open')}>Open</Button><Button size="small" icon={<ArrowDownloadRegular/>} onClick={()=>action('Download')}>Download</Button></div></div><div className={s.paneSection}><div className={s.sectionTitle}>Properties{iconButton('Edit properties',<EditRegular/>,()=>setDialog('Edit details'))}</div><div className={s.props}><Text className={s.secondary}>Document type</Text><span>{current.type}</span><Text className={s.secondary}>Status</Text><span>{status(current)}</span><Text className={s.secondary}>Expiry date</Text><span>{current.expiry}</span><Text className={s.secondary}>Description</Text><span>Agreement covering the scope of services and commercial terms for Contoso Ltd.</span></div></div><div className={s.paneSection}><div className={s.sectionTitle}>Activity</div><DocumentPerson name={current.by} secondaryText="Modified by" activity/><DocumentPerson name="Michael Bose" secondaryText="Created by" activity/><div className={s.props}><Text className={s.secondary}>Modified</Text><span>{current.modified}</span><Text className={s.secondary}>Created</Text><span>September 1, 2026</span></div></div><div className={s.paneSection}><div className={s.sectionTitle}>Storage</div><div className={s.props}><Text className={s.secondary}>Source</Text><span>{current.source}</span><Text className={s.secondary}>File size</Text><span>{current.size}</span></div>{current.source==='SharePoint'&&<div className={s.hint}>Access to this file is controlled by SharePoint permissions.</div>}</div></>:<div className={s.empty}><DocumentRegular fontSize={44}/><p>{selected.length?`${selected.length} documents selected`:'Select a document to see details'}</p>{selected.length>1&&<Button onClick={()=>action('Edit details')}>Edit details</Button>}</div>}</InlineDrawer>}
 </div><div aria-live="polite" style={{position:'absolute',width:1,height:1,overflow:'hidden'}}>{selected.length} items selected</div></section>
 <div className={s.secondary} style={{marginTop:16}}>Visual prototype · Sample documents and simulated actions</div></main></div>
 <OverlayDrawer open={dialog==='Edit details'} position="end" className={s.editDrawer} onOpenChange={(_,d)=>!d.open&&setDialog(null)}>
 <DrawerHeader><DrawerHeaderTitle action={<Button appearance="subtle" aria-label="Close edit details" icon={<DismissRegular/>} onClick={()=>setDialog(null)}/>}>Edit details</DrawerHeaderTitle><Text className={s.secondary}>{picked.length===1?current?.name:`${picked.length} documents selected`}</Text></DrawerHeader>
 <DrawerBody><div className={s.dialogFields}><Field label="Document type" required><Dropdown defaultValue={current?.type}>{['Contract','Proposal','Finance','Legal','Media','Other'].map(t=><Option key={t}>{t}</Option>)}</Dropdown></Field><Field label="Status"><Dropdown defaultValue={current?.status}><Option>Draft</Option><Option>Active</Option><Option>Archived</Option></Dropdown></Field><Field label="Expiry date"><Input type="date" defaultValue="2026-10-24"/></Field><Field label="Description"><Textarea resize="vertical" defaultValue="Agreement covering the scope of services and commercial terms for Contoso Ltd."/></Field><Field label="Department"><Dropdown defaultValue={current?.department}><Option>Legal</Option><Option>Sales</Option><Option>Finance</Option><Option>Operations</Option></Dropdown></Field></div></DrawerBody>
 <DrawerFooter><Button appearance="primary" onClick={()=>{setDialog(null);feedback('Changes saved · Visual demonstration only');}}>Save</Button><Button onClick={()=>setDialog(null)}>Cancel</Button></DrawerFooter>
 </OverlayDrawer>
 <Dialog open={!!dialog&&dialog!=='Edit details'} onOpenChange={(_,d)=>!d.open&&setDialog(null)}><DialogSurface><DialogBody><DialogTitle>{dialog==='Preview'||dialog==='Open'?current?.name:dialog}</DialogTitle><DialogContent>{dialog==='Delete'?<p>{selected.length} document{selected.length===1?'':'s'} selected.<br/>{picked.some(d=>d.source==='Note')&&<>This permanently deletes the document and its file.<br/></>}{picked.some(d=>d.source==='SharePoint')&&<>This removes the reference only. The file in SharePoint is not deleted.</>}</p>:dialog==='Edit details'?<div className={s.dialogFields}><Field label="Document type"><Dropdown defaultValue={current?.type}>{['Contract','Proposal','Finance','Legal','Media','Other'].map(t=><Option key={t}>{t}</Option>)}</Dropdown></Field><Field label="Status"><Dropdown defaultValue={current?.status}><Option>Draft</Option><Option>Active</Option><Option>Archived</Option></Dropdown></Field><Field label="Description"><Textarea defaultValue="Agreement covering the scope of services and commercial terms for Contoso Ltd."/></Field></div>:dialog==='Add link'?<div className={s.dialogFields}><Field label="SharePoint URL" required><Input placeholder="https://contoso.sharepoint.com/…"/></Field><Field label="Display name"><Input placeholder="Document name"/></Field><Text className={s.secondary}>The file stays in SharePoint. Its existing permissions apply.</Text></div>:dialog==='Upload'?<div className={s.preview}><ArrowUploadRegular fontSize={48}/><Text weight="semibold">Drop files here to upload</Text><Text className={s.secondary}>The upload experience will be connected after design approval.</Text><Button appearance="primary" onClick={()=>{setDialog(null);feedback('Upload demonstration · 2 files queued');}}>Simulate upload</Button></div>:dialog==='Keyboard shortcuts'?<p>Click to select · Ctrl/Cmd + click to add<br/>Shift + click to select a range<br/>Space to toggle · Ctrl/Cmd + A to select all<br/>Enter to preview · Esc to clear</p>:<div className={s.preview}>{current&&<DocumentThumbnail doc={current} icon={<FileIcon doc={current} large/>}/>}</div>}</DialogContent><DialogActions><Button appearance="secondary" onClick={()=>setDialog(null)}>Close</Button>{['Delete','Edit details','Add link'].includes(dialog)&&<Button appearance="primary" onClick={()=>{if(dialog==='Delete'){setRows(rows.filter(d=>!selected.includes(d.id)));setSelected([]);feedback('Documents removed from the preview. Reload to restore.');}else feedback(`${dialog==='Edit details'?'Changes saved':'Link added'} · Visual demonstration only`);setDialog(null);}}>{dialog==='Delete'?'Delete':dialog==='Add link'?'Add link':'Save'}</Button>}</DialogActions></DialogBody></DialogSurface></Dialog>
 </FluentProvider>
}
// The authenticated host may supply a loader before mounting. No token is stored here.
ReactDOM.render(<UserPhotoProvider loader={window.dmsUserPhotoLoader}><App/></UserPhotoProvider>,document.getElementById('root'));
