import { chromium } from '@playwright/test';
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1050},deviceScaleFactor:1,reducedMotion:'reduce'});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:5173');
await page.getByRole('heading',{name:'Documents',exact:true}).waitFor();
await page.locator('img[src*="/icons/"]').first().waitFor();
await page.waitForFunction(()=>[...document.querySelectorAll('img[src*="/icons/"]')].every(img=>img.complete&&img.naturalWidth>0));
await page.screenshot({path:'screenshots/01-list.png',fullPage:true,animations:'disabled'});
await page.getByRole('row').filter({hasText:'Master Services Agreement.docx'}).click();
await page.getByRole('button',{name:'Details',exact:true}).click();
await page.screenshot({path:'screenshots/02-details.png',fullPage:true,animations:'disabled'});
await page.getByRole('button',{name:'Edit properties',exact:true}).click();
await page.getByRole('button',{name:'Close edit details',exact:true}).waitFor();
await page.screenshot({path:'screenshots/10-edit-drawer.png',fullPage:false,animations:'disabled'});
await page.getByRole('button',{name:'Close edit details',exact:true}).click();
await page.getByRole('button',{name:'Close details'}).click();
await page.getByRole('button',{name:'1 selected'}).click();
await page.getByRole('button',{name:'Switch view'}).click();
await page.getByRole('menuitem',{name:'Tiles view'}).click();
await page.mouse.move(0,0);
await page.screenshot({path:'screenshots/03-tiles.png',fullPage:true,animations:'disabled'});
await page.getByRole('option').filter({hasText:'Master Services Agreement.docx'}).hover();
await page.screenshot({path:'screenshots/12-card-hover.png',fullPage:true,animations:'disabled'});
await page.mouse.move(0,0);
await page.getByRole('button',{name:'Blue',exact:true}).click();
await page.getByRole('button',{name:'Notes',exact:true}).click();
await page.getByRole('button',{name:'New',exact:true}).click();
await page.screenshot({path:'screenshots/04-sharepoint.png',fullPage:true,animations:'disabled'});
await page.keyboard.press('Escape');
await page.getByRole('button',{name:'Dark',exact:true}).click();
await page.screenshot({path:'screenshots/05-dark.png',fullPage:true,animations:'disabled'});
await page.getByRole('button',{name:'High contrast',exact:true}).click();
await page.screenshot({path:'screenshots/06-high-contrast.png',fullPage:true,animations:'disabled'});
await page.getByRole('button',{name:'Teal',exact:true}).click();
await page.getByRole('option').filter({hasText:'Site Photo.jpg'}).click();
await page.getByRole('button',{name:'Details',exact:true}).click();
await page.waitForFunction(()=>[...document.querySelectorAll('img[src*="/previews/"]')].every(img=>img.complete&&img.naturalWidth>0));
await page.screenshot({path:'screenshots/11-photo-details.png',fullPage:true,animations:'disabled'});
console.log(JSON.stringify({errors,title:await page.title()}));
await browser.close();
