import assert from 'node:assert/strict';
import {chromium} from '@playwright/test';
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1050}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:5173/');
await page.getByRole('heading',{name:'Documents',exact:true}).waitFor();
const first=page.getByRole('row').filter({hasText:'Master Services Agreement.docx'});
await first.click();
await page.getByRole('checkbox',{name:'Select Q3 Proposal.pptx',exact:true}).click();
await page.getByRole('button',{name:'2 selected',exact:true}).waitFor();
await page.screenshot({path:'screenshots/07-selection.png',fullPage:true});
await page.getByRole('button',{name:'Switch view'}).click();
await page.getByRole('menuitem',{name:'Tiles view'}).click();
assert.equal(await page.locator('[role="option"][aria-selected="true"]').count(),2);
await page.getByRole('button',{name:'2 selected',exact:true}).click();
await page.getByRole('button',{name:'Switch view'}).click();
await page.getByRole('menuitem',{name:'List view'}).click();
await page.getByRole('textbox',{name:'Search documents'}).fill('Pricing');
assert.equal(await page.locator('[data-document-id]').count(),1);
await page.getByRole('textbox',{name:'Search documents'}).fill('no-such-file');
await page.getByRole('heading',{name:'No results match your search or filters'}).waitFor();
await page.getByRole('button',{name:'Clear filters',exact:true}).click();
assert.equal(await page.locator('[data-document-id]').count(),12);
await page.getByRole('button',{name:'Notes',exact:true}).click();
await page.getByRole('button',{name:'New',exact:true}).click();
await page.getByRole('menuitem',{name:'Link',exact:true}).click();
await page.getByRole('dialog').waitFor();
await page.screenshot({path:'screenshots/08-add-link.png',fullPage:true});
await page.getByRole('button',{name:'Close',exact:true}).click();
await page.getByRole('button',{name:'SharePoint links',exact:true}).click();
for(const width of [320,480,720,1024,1440]){
 await page.setViewportSize({width,height:1000});
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);
 assert.equal(overflow,false,`No horizontal page overflow at ${width}`);
 if(width===320)await page.screenshot({path:'screenshots/09-mobile.png',fullPage:true});
}
assert.equal(await page.locator('[role="grid"].fui-DataGrid').count(),1);
await page.waitForFunction(()=>[...document.querySelectorAll('img[src*="/icons/"]')].every(img=>img.complete&&img.naturalWidth>0));
assert.equal(await page.locator('.fui-Persona').count(),12);
await page.waitForFunction(()=>[...document.querySelectorAll('img[src*="/previews/"]')].every(img=>img.complete&&img.naturalWidth>0));
assert.deepEqual(errors,[]);
console.log('PASS: shared multi-selection, List/Tiles switch, search, empty results, link dialog, no page overflow at 320/480/720/1024/1440, no browser runtime errors.');
await browser.close();
